name: Publish Python

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.8'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: MPP
          use-mamba: true

      - name: Install environment
        shell: bash -l {0}
        run: |
          pip install poetry

      - name: Poetry upload
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.PyPI_PyWLK }}
        shell: bash -l {0}
        run: |
          poetry config pypi-token.pypi "$POETRY_PYPI_TOKEN"
          poetry publish --build
